import fs from 'fs';
import path from 'path';
import { exec } from 'child_process';
import { promisify } from 'util';

const execAsync = promisify(exec);

export class GitHubExportService {
  async generateProject(config: any, outputDir: string) {
    await this.createDirectoryStructure(outputDir);
    await this.generateFrontendFiles(config, path.join(outputDir, 'frontend'));
    await this.generateBackendFiles(config, path.join(outputDir, 'backend'));
    await this.generateRootFiles(config, outputDir);
    
    return outputDir;
  }

  private async createDirectoryStructure(baseDir: string) {
    const dirs = [
      'frontend/src/components',
      'frontend/src/pages',
      'frontend/src/lib',
      'backend/src/routes',
      'backend/src/models',
      'backend/src/middleware'
    ];

    for (const dir of dirs) {
      await fs.promises.mkdir(path.join(baseDir, dir), { recursive: true });
    }
  }

  private async generateFrontendFiles(config: any, frontendDir: string) {
    const packageJson = {
      name: config.app?.name?.toLowerCase().replace(/\s+/g, '-') || 'generated-app',
      version: config.app?.version || '1.0.0',
      scripts: {
        dev: 'next dev',
        build: 'next build',
        start: 'next start'
      },
      dependencies: {
        'next': '^14.0.0',
        'react': '^18.0.0',
        'react-dom': '^18.0.0'
      }
    };

    await fs.promises.writeFile(
      path.join(frontendDir, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    const indexPage = `export default function Home() {
  return <div><h1>${config.app?.name || 'Generated App'}</h1></div>;
}`;

    await fs.promises.writeFile(
      path.join(frontendDir, 'src/pages/index.tsx'),
      indexPage
    );
  }

  private async generateBackendFiles(config: any, backendDir: string) {
    const packageJson = {
      name: `${config.app?.name?.toLowerCase().replace(/\s+/g, '-')}-backend` || 'generated-backend',
      version: config.app?.version || '1.0.0',
      scripts: {
        start: 'node src/index.js',
        dev: 'nodemon src/index.js'
      },
      dependencies: {
        express: '^4.18.0',
        cors: '^2.8.5',
        dotenv: '^16.0.0'
      }
    };

    await fs.promises.writeFile(
      path.join(backendDir, 'package.json'),
      JSON.stringify(packageJson, null, 2)
    );

    const indexJs = `const express = require('express');
const cors = require('cors');
const app = express();

app.use(cors());
app.use(express.json());

app.get('/', (req, res) => {
  res.json({ message: '${config.app?.name || 'Generated App'} API' });
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => console.log(\`Server running on port \${PORT}\`));`;

    await fs.promises.writeFile(
      path.join(backendDir, 'src/index.js'),
      indexJs
    );
  }

  private async generateRootFiles(config: any, rootDir: string) {
    const readme = `# ${config.app?.name || 'Generated Application'}

${config.app?.description || 'Generated by Dynamic App Generator'}

## Setup

### Backend
\`\`\`bash
cd backend
npm install
npm run dev
\`\`\`

### Frontend
\`\`\`bash
cd frontend
npm install
npm run dev
\`\`\`
`;

    await fs.promises.writeFile(path.join(rootDir, 'README.md'), readme);

    const configJson = JSON.stringify(config, null, 2);
    await fs.promises.writeFile(path.join(rootDir, 'config.json'), configJson);
  }

  async initGitRepo(projectDir: string) {
    await execAsync('git init', { cwd: projectDir });
    await execAsync('git add .', { cwd: projectDir });
    await execAsync('git commit -m "Initial commit from Dynamic App Generator"', { cwd: projectDir });
  }

  async pushToGitHub(projectDir: string, repoUrl: string, token?: string) {
    const remote = token 
      ? repoUrl.replace('https://', `https://${token}@`)
      : repoUrl;

    await execAsync(`git remote add origin ${remote}`, { cwd: projectDir });
    await execAsync('git branch -M main', { cwd: projectDir });
    await execAsync('git push -u origin main', { cwd: projectDir });
  }

  async exportProject(config: any, options: { repoUrl?: string; token?: string } = {}) {
    const timestamp = Date.now();
    const projectName = config.app?.name?.toLowerCase().replace(/\s+/g, '-') || 'generated-app';
    const outputDir = path.join('/tmp', `${projectName}-${timestamp}`);

    await this.generateProject(config, outputDir);
    await this.initGitRepo(outputDir);

    if (options.repoUrl) {
      await this.pushToGitHub(outputDir, options.repoUrl, options.token);
    }

    return { path: outputDir, success: true };
  }
}

export default new GitHubExportService();
